### ISSUE TITLE
Is this still related to SIXpay?

### ISSUE THREAD

**Issue by ThiefMaster** [adityamj/indico-payment-razorpay#1]
> This plugin provides a payment option for Indico's payment module using the Razorpay Web Checkout API **SIXPay Saferpay** API.

If not, this is probably a copy&paste mistake in the README...

**Comment by adityamj** [comment]
This is fixed in #[3566846](https://github.com/adityamj/indico-payment-razorpay/commit/3566846454ba2884b5dbeb9bb5b3c7970165557f)
